# Generated by Django 2.2.5 on 2019-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(default='Unofficial', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
