# Generated by Django 2.2.5 on 2019-10-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='onteam',
            field=models.BooleanField(default=False),
        ),
    ]
