# Generated by Django 2.2.5 on 2019-11-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comp_onteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='event',
            field=models.CharField(choices=[('VPO', 'Varsity Policy'), ('VLD', 'Varsity Lincoln Douglas'), ('VPF', 'Varsity Public Forum'), ('NPO', 'Novice Policy'), ('NLD', 'Novice Lincoln Douglas'), ('NPF', 'Novice Public Forum')], default='VPO', max_length=100),
        ),
    ]
