# Generated by Django 2.2.5 on 2019-11-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191101_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='varsity',
        ),
    ]
