# Generated by Django 3.0.5 on 2020-05-17 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200517_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
